### ISSUE TITLE
Long program names are not always visible in Tree View

### ISSUE THREAD

**Issue by gtackett** [NationalSecurityAgency/ghidra#1858]
**Describe the bug**
In the Tree View of the project, long program names are not fully visible in some circumstances.

And strangely enough, if you select a program and choose "Rename" from the pop-up menu, but then click on another program without renaming the first, the entire program name becomes visible.

**To Reproduce**
If possible, I will provide a sample project and/or instructions on reproducing the. In the mean time, the attached screen shot will at least show you the problem I'm looking at.

**Expected behavior**
I expect there to be an easy way to see the entire name of a program.

**Screenshots**
Multiple programs with long names that have been truncated to "..."
![image](https://user-images.githubusercontent.com/52077/81837364-c5e09080-9512-11ea-9aac-77c554cc56dc.png)

**Environment (please complete the following information):**
 - OS: MacOS 10.13.6
 - Java Version: 12.0.1

**Comment by emteere** [comment]
Does this always occur?  You mention in some circumstances.
It looks like your files are in sub-folders.

I'm using master and on Linux and I can't re-produce.
So it is possible it is fixed, or just happens on Mac.

**Comment by gtackett** [comment]
This archive:
[GhidraSupport_2020_05_13.gar.zip](https://github.com/NationalSecurityAgency/ghidra/files/4623997/GhidraSupport_2020_05_13.gar.zip)

 looks like this for me:

![Capto_Capture 2020-05-13_02-42-35_PM](https://user-images.githubusercontent.com/52077/81851773-00a0f380-9528-11ea-9a76-ce3f4e2a16d2.png)

**Comment by emteere** [comment]
Looks like maybe a Mac issue.  I can't duplicate in 9.1.2 or in Master.

Could also be a JAVA 12 thing.  I'm using 11.

**Comment by astrelsky** [comment]
> Looks like maybe a Mac issue. I can't duplicate in 9.1.2 or in Master.
> 
> Could also be a JAVA 12 thing. I'm using 11.

It might be. I get the truncated names as well on windows using Java 14

**Comment by ryanmkurtz** [comment]
I use Amazon Corretto 11 and I don't see the problem on Windows.  I just tried AdoptOpenJDK 12 and 14 on Windows and still don't see the problem.  This is out of master.  I should note that my Ghidra is still compiled with Amazon Corretto 11 out of Eclipse when launching with 12 and 14...not sure if that matters.  I'll experiment more tomorrow.

**Comment by ryanmkurtz** [comment]
Just tried Ghidra 9.1.2 on macOS with Amazon Corretto 11 and AdoptOpenJdk 12 and I don't see the problem.

**Comment by astrelsky** [comment]
> Just tried Ghidra 9.1.2 on macOS with Amazon Corretto 11 and AdoptOpenJdk 12 and I don't see the problem.

There is probably more to this. I just attempted to reproduce it again and did not encounter the problem this time.

**Comment by ryanmkurtz** [comment]
Possibly related to this: https://stackoverflow.com/questions/10374161/jtree-convertvaluetotext-return-is-truncated-when-with-changed

**Comment by dev747368** [comment]
I'm seeing an issue in master when the file has version information appended to the end of the name in the tree.  (which seems to be your case @gtackett )  This issue didn't show up for me in the 9.1.2 build.
I'll keep you updated.

**Comment by gtackett** [comment]
> 
> 
> I'm seeing an issue in master when the file has version information appended to the end of the name in the tree. (which seems to be your case @gtackett )...
> I'll keep you updated.

@dev747368 you are correct, and thanks!

**Comment by dev747368** [comment]
Pretty sure 4d48d6f180b28fd555326bacfe8eb0cc989546cf fixed this.  Reopen if not.
