### ISSUE TITLE
Incorrect decompilation of calls to functions with varargs and custom storage

### ISSUE THREAD

**Issue by RootCubed** [NationalSecurityAgency/ghidra#4334]
**Describe the bug**
(Note: this bug can currently only be experienced after applying a patch that fixes another bug relating to this issue, see section "Additional context")
Decompiling a call to a function that is marked with varargs and has the parameters set to custom storage gives incorrect results.

**To Reproduce**
1. Download the demo source and object file from the attachments section.
2. Import `varargs_custom_storage.o` into Ghidra (language: big-endian PowerPC 32bit, default)
3. Run auto analysis.
4. Edit the function `call_function_with_varargs` as follows:
 - Check "Varargs"
 - Check "Use Custom Storage"
 - Set the first argument to datatype `void *` and set the storage to the register `r12`.
5. Navigate to the function `main`.
6. Observe that the function call incorrectly decompiles to `call_function_with_varargs(NULL, 1, 2, 3);`

**Expected behavior**
The function call should decompile to `call_function_with_varargs(called_function, 0, 1, 2, 3);`.

**Attachments**
[varargs_custom_storage.zip](https://github.com/NationalSecurityAgency/ghidra/files/8884464/varargs_custom_storage.zip)

**Environment:**
 - OS: Windows 11
 - Java Version: 15.0.1
 - Ghidra Version: 10.2-DEV
 - Ghidra Origin: locally built from https://github.com/RootCubed/ghidra/tree/fix_nullpointercrash_fspec

**Additional context**
The decompiler process dies while decompiling the function `main` when the commit https://github.com/RootCubed/ghidra/commit/0e45f7f09fa2a45051e252f2e5b86343722473db is not applied. This bug has been reported in a separate pull request: (TODO: link once opened)

**Comment by RootCubed** [comment]
@ryanmkurtz Is it possible that this issue slipped through the cracks? Noticed that it didn't have any labels assigned yet.

Since the NPE got fixed in the meantime, it is no longer necessary to apply the provided patch, the issue is now reproducible on master.

**Comment by jonko0493** [comment]
![image](https://github.com/user-attachments/assets/8b4a2c4b-011b-4727-8224-50f165cd2c34)

I'm running into this issue with the PowerPC decompiler specifically. We have varargs `printf` type functions which are being marked as using custom storage and therefore not fixed up by the variadic function signature override analyzer. Pretty unfortunate as these lengthy method signatures mess with the signatures of all the functions that call them, leading to an untenable chain of manual fixups. If anyone has advice, I'd appreciate it of course, but I'd love to have this issue fixed.

**Comment by LukeSerne** [comment]
I looked at this issue a bit today, hoping I'd find a solution. I did not manage to, so I'm leaving my notes here:

While playing around with the example files, I noticed that the `r12` first argument is initially correctly identified by the decompiler, only to be discarded at the very end. I loaded the provided object file in Ghidra, generated a debug xml, and then used my [DecompVis](https://www.github.com/LukeSerne/DecompVis) tool to see the intermediate states of P-Code:

<img width="914" height="798" alt="Image" src="https://github.com/user-attachments/assets/488b689a-2b4e-4358-b824-1c643ebd24a3" />

Only in the `activeparam` step, the first argument is removed.

When digging into that, I found that that happens because:
1. `FuncCallSpecs::buildInputFromTrials` considers the `r12` parameter unused, because
2. `ParamListStandard::buildTrialMap` (called by `ParamListStandard::fillinMap`, called by `ProtoModel::deriveInputMap`, called by `FuncProto::deriveInputMap`) marks the `r12` parameter as unused, because
3. `ParamListStandard::findEntry` returns `NULL` for the `r12` param (and it doesn't for the other params), because
4. It tries to look up `r12` in the possible parameter storage locations for the default calling convention, as defined in the `.cspec` file, and fails because normally `r12` is `unaffected`.

Consequently, if we change the custom storage location of the function pointer from `r12` to a register that is defined in the prototype definition that the `call_function_with_varargs` uses in https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Processors/PowerPC/data/languages/ppc_32.cspec, such as `r9`, we should see correct decompilation. Manually changing the assembly of `main` to change usages of `r12` into `r9`, and changing the function prototype of `call_function_with_varargs` to use varargs and have the function pointer in `r9` instead of `r9`, the decompilation result is improved (the `called_function` pointer is recognised and kept as first argument)! 🥳 

```C
void main(void)

{
  undefined4 in_r7;
  undefined4 in_r8;
  
  call_function_with_varargs(called_function,0,1,2,3,in_r7,in_r8);
  return;
}
```

Note that `r10` also didn't work (same result as `r12`), and using `r9` isn't a perfect solution - the decompiler detects two extra arguments (`in_r7` and `in_r8`). It seems that the combination of varargs and custom storage works slightly better for some other registers (in this case `r7`, `r8` and `r9`), probably because those are included in the definition of the calling convention that is used for the `call_function_with_varargs` function. But why doesn't `r10` work, even though it is also included in the same definition?

If I remove `varargs` and use custom storage and hardcode the number of arguments, the `activeparam` rule doesn't apply. Also if I don't use custom storage, the `activeparam` rule doesn't apply. It seems like `activeparam` is only used for determining the arguments of function with an unknown number of arguments (either because they have not been defined yet or because it's a variadic function). Perhaps the `activeparam` rule should be updated to ensure that it doesn't remove known good parameters, even if they are in unexpected storage locations, but I'm not sure how.
