### ISSUE TITLE
Initial CS from MZ header does not adjust CS of entry point

### ISSUE THREAD

**Issue by carlreinke** [NationalSecurityAgency/ghidra#5700]
The initial relative CS from the MZ header should adjust the segment of the entry point.

## Steps to Reproduce
1. Import "test-1.exe" from [test-1.zip](https://github.com/NationalSecurityAgency/ghidra/files/12415388/test-1.zip).  This is a self-modifying DOS program that sets `ERRORLEVEL 1`.
2. Analyze.
3. Memory map does not have a block for segment `103e`, and entry point has `assume CS = 0x1000` even though the initial relative CS is 0x3e in the MZ header.
4. During analysis, the incorrect assumed value of CS causes incorrect references to be created.

Memory map:
Name | Start | End | Length | R | W | X | Volatile | Overlay | Type | Initialized | Byte Source | Source
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CODE_0 | 1000:0000 | 1000:982f | 0x9830 | true | true | true | false | false | Default | true | File: test-fail.exe: 0x120 | mz
CODE_1 | 1983:0000 | 1983:ab59 | 0xab5a | true | true | true | false | false | Default | true | File: test-fail.exe: 0x9950 | mz
DATA | 1983:ab5a | 1983:f659 | 0x4b00 | true | true | false | false | false | Default | false |   | mz
HEADER | OTHER:00000000 | OTHER:0000011f | 0x120 | false | false | false | false | true | Default | true | File: test-fail.exe: 0x0 | 

Entry point:
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined __cdecl16near entry()
                               assume CS = 0x1000
                               assume DS = 0x1983
                               assume SP = 0x4af4
                               assume SS = 0x2439
             undefined         AL:1           <RETURN>
                             entry                                              XREF[1]:     Entry Point(*)  
      1000:03e8 ba 83 19        MOV        DX,0x1983                                       0
             assume SS = <UNKNOWN>
             assume SP = <UNKNOWN>
      1000:03eb 2e c6 06        MOV        byte ptr CS:[DAT_1000_0012],0x1                 0
                12 00 01
      1000:03f1 b8 00 4c        MOV        AX,0x4c00                                       0
      1000:03f4 cd 21           INT        0x21                                            0
      1000:03f6 c3              RET                                                      - ? -
```

## Expected behavior

There should be a block for segment `103e` in the memory map, and that segment should `assume CS = 0x103e`.  References should be created based on the correct CS.

Memory map:
Name | Start | End | Length | R | W | X | Volatile | Overlay | Type | Initialized | Byte Source | Source
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CODE_0 | 1000:0000 | 1000:03df | 0x3e0 | true | true | true | false | false | Default | true | File: test-fail.exe: 0x120 | mz
CODE_1 | 103e:0000 | 103e:944f | 0x9450 | true | true | true | false | false | Default | true | File: test-fail.exe: 0x500 | mz
CODE_2 | 1983:0000 | 1983:ab59 | 0xab5a | true | true | true | false | false | Default | true | File: test-fail.exe: 0x9950 | mz
DATA | 1983:ab5a | 1983:f659 | 0x4b00 | true | true | false | false | false | Default | false |   | mz
HEADER | OTHER:00000000 | OTHER:0000011f | 0x120 | false | false | false | false | true | Default | true | File: test-fail.exe: 0x0 |  

Entry point:
```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined __cdecl16near entry()
                               assume CS = 0x103e
                               assume DS = 0x1983
                               assume SP = 0x4af4
                               assume SS = 0x2439
             undefined         AL:1           <RETURN>
                             entry                                              XREF[1]:     Entry Point(*)  
      103e:0008 ba 83 19        MOV        DX,0x1983                                       0
             assume SS = <UNKNOWN>
             assume SP = <UNKNOWN>
      103e:000b 2e c6 06        MOV        byte ptr CS:[LAB_103e_0011+1],0x1               0
                12 00 01
                             LAB_103e_0011+1                                    XREF[0,1]:   103e:000b(W)  
      103e:0011 b8 00 4c        MOV        AX,0x4c00                                       0
      103e:0014 cd 21           INT        0x21                                            0
      103e:0016 c3              RET                                                      - ? -
```

## Environment
 - OS: Windows 10
 - Java Version: 19.0.1
 - Ghidra Version: 10.3.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
In your "Expected behavior" listing, did you manually type in
```
MOV        byte ptr CS:[LAB_103e_0011+1],0x1
```
or did you make code changes to generate that?

**Comment by carlreinke** [comment]
With some effort (split the block at 103e, set the value of CS, disassemble, clear code bytes, disassemble again, create the function, and edit the segment in the reference), I can get Ghidra to produce that exact listing.

**Comment by carlreinke** [comment]
Testing this out, I see that the segment is created in the memory map and CS now assumes the correct value.  However, the reference created by analysis is still incorrect.

```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined __cdecl16near entry()
                               assume CS = 0x103e
                               assume DS = 0x1983
                               assume SP = 0x4af4
                               assume SS = 0x2439
             undefined         AL:1           <RETURN>
                             entry                                                XREF[1]:     Entry Point(*)  
       103e:0008 ba 83 19        MOV        DX,0x1983                                       0
             assume SS = <UNKNOWN>
             assume SP = <UNKNOWN>
       1000:03eb 2e c6 06        MOV        byte ptr CS:[DAT_1000_0012],0x1                 0
                 12 00 01
       1000:03f1 b8 00 4c        MOV        AX,0x4c00                                       0
       1000:03f4 cd 21           INT        0x21                                            0
       103e:0016 c3              RET                                                      - ? -
```

(And mysteriously -- but of less importance -- the segment shows as "1000" for instruction addresses in the middle of the function.  Doing "clear code bytes" and "disassemble" causes it to show the expected segment, which then persists even if you undo.)

**Comment by ryanmkurtz** [comment]
Yes sorry, this ticket turned into 3 separate issues being solved by 3 different people.  I'll reopen it.

**Comment by emteere** [comment]
We noticed the strangeness in the address displayed, which is an artifact of not handling the segment address correctly somewhere in the block creation routines.  In segmented address is keeps it separately.  However something must have pulled the offset out and used it which has the combined segment:offset in a value.

There is a change for RealMode that we've been considering that will split the CS out and not incorrectly try to compute it from the combined segment:offset value, which is what is occuring here.  It should fix the reference issue to use the correct segment.  It does mean that the CS must be set at the beginning of functions correctly.

@carlreinke, @Wall-AF, You can try it out if you'd like for RealMode programs.  There are some other issues that still need to be ironed out.  But it will allow the decompiler to know the CS value in RealMode, as well as the constant analysis.

```
diff --git a/Ghidra/Processors/x86/data/languages/ia.sinc b/Ghidra/Processors/x86/data/languages/ia.sinc
index 44a99bc..e02bbbf 100644
--- a/Ghidra/Processors/x86/data/languages/ia.sinc
+++ b/Ghidra/Processors/x86/data/languages/ia.sinc
@@ -753,7 +753,7 @@
 addr64: [Base64 + Index64*ss]			is mod=2 & r_m=4; Index64 & Base64 & ss; imm32=0   { local tmp=Base64+Index64*ss; export tmp; }
 @endif
 
-currentCS: CS is protectedMode=0 & CS { tmp:4 = (inst_next >> 4) & 0xf000; CS = tmp:2; export CS; }
+currentCS: CS is protectedMode=0 & CS { export CS; }   # can't accurately compute the 16-bit segment, rely on it being set
 currentCS: CS is protectedMode=1 & CS { tmp:4 = (inst_next >> 16) & 0xffff; CS = tmp:2; export CS; }
  
 segWide: is segover=0		        { export 0:$(SIZE); }
@@ -795,8 +795,24 @@
 @endif
 Mem: segWide^addr32 is $(LONGMODE_OFF) & addrsize=1 & segWide & highseg=1; addr32 	{ tmp:$(SIZE) = segWide + zext(addr32); export tmp; }
 
-rel8: reloc is simm8        [ reloc=inst_next+simm8; ] { export *[ram]:$(SIZE) reloc; }
-rel16: reloc is simm16      [ reloc=((inst_next >> 16) << 16) | ((inst_next + simm16) & 0xFFFF); ] { export *[ram]:$(SIZE) reloc; }
+rel8:      reloc is simm8        [ reloc=inst_next+simm8; ] { export *[ram]:$(SIZE) reloc; }
+
+@ifdef IA64
+# never use segmenting in 64-bit code
+rel16_val: reloc is simm16      [ reloc= inst_next + simm16; ]             { local target:$(SIZE) = reloc; export target; }
+@else
+rel16_val: reloc is protectedMode=0 & simm16 & currentCS [ reloc= inst_next + simm16; ] {
+	# isolate real offset, by removing shifted segment value
+	local curCS:$(SIZE) = zext(currentCS) << 4;
+	local real_off:$(SIZE) = (reloc - curCS);
+	real_off = segment(currentCS, real_off:2);
+	export real_off;
+}
+rel16_val: reloc is protectedMode=1 & simm16      [ reloc=((inst_next >> 16) << 16) | ((inst_next + simm16) & 0xFFFF); ] {
+	local target:$(SIZE) = reloc; export target;
+}
+@endif
+
 rel32: reloc is simm32      [ reloc=inst_next+simm32; ] { export *[ram]:$(SIZE) reloc; }
 
 
@@ -2089,17 +2105,17 @@
 :BTS Rmr64,imm8     is $(LONGMODE_ON) & vexMode=0 & opsize=2 & byte=0xf; byte=0xba; mod=3 & Rmr64 & reg_opcode=5; imm8   { local bit=imm8&0x3f; local val=(Rmr64>>bit)&1; Rmr64=Rmr64 | (1<<bit); CF=(val!=0); }
 @endif
 
-:CALL rel16     is $(LONGMODE_OFF) & vexMode=0 & addrsize=0 & opsize=0 & byte=0xe8; rel16     { push22(&:2 inst_next); call rel16; }
-:CALL rel16     is $(LONGMODE_OFF) & vexMode=0 & addrsize=1 & opsize=0 & byte=0xe8; rel16     { push42(&:2 inst_next); call rel16; }
+:CALL rel16_val     is $(LONGMODE_OFF) & vexMode=0 & addrsize=0 & opsize=0 & byte=0xe8; rel16_val     { push22(&:2 inst_next); call [rel16_val]; }
+:CALL rel16_val     is $(LONGMODE_OFF) & vexMode=0 & addrsize=1 & opsize=0 & byte=0xe8; rel16_val     { push42(&:2 inst_next); call [rel16_val]; }
 @ifdef IA64
-:CALL rel16     is $(LONGMODE_ON) & vexMode=0 & opsize=0 & byte=0xe8; rel16     { push88(&:8 inst_next); call rel16; }
+:CALL rel16_val     is $(LONGMODE_ON) & vexMode=0 & opsize=0 & byte=0xe8; rel16_val                   { push88(&:8 inst_next); call [rel16_val]; }
 @endif
 
 #  When is a Call a Jump, when it jumps right after.  Not always the case but...
-:CALL rel16     is $(LONGMODE_OFF) & vexMode=0 & addrsize=0 & opsize=0 & byte=0xe8; simm16=0 & rel16      { push22(&:2 inst_next); goto rel16; }
-:CALL rel16     is $(LONGMODE_OFF) & vexMode=0 & addrsize=1 & opsize=0 & byte=0xe8; simm16=0 & rel16      { push42(&:2 inst_next); goto rel16; }
+:CALL rel16_val     is $(LONGMODE_OFF) & vexMode=0 & addrsize=0 & opsize=0 & byte=0xe8; simm16=0 & rel16_val      { push22(&:2 inst_next); goto [rel16_val]; }
+:CALL rel16_val     is $(LONGMODE_OFF) & vexMode=0 & addrsize=1 & opsize=0 & byte=0xe8; simm16=0 & rel16_val      { push42(&:2 inst_next); goto [rel16_val]; }
 @ifdef IA64
-:CALL rel16     is $(LONGMODE_ON) & vexMode=0 & opsize=0 & byte=0xe8; simm16=0 & rel16      { push88(&:8 inst_next); goto rel16; }
+:CALL rel16_val     is $(LONGMODE_ON) & vexMode=0 & opsize=0 & byte=0xe8; simm16=0 & rel16_val      { push88(&:8 inst_next); goto [rel16_val]; }
 @endif
 
 :CALL rel32     is $(LONGMODE_OFF) & vexMode=0 & addrsize=0 & opsize=1 & byte=0xe8; rel32     { push24(&:4 inst_next); call rel32; }
@@ -2826,7 +2842,7 @@
 @endif
 
 :J^cc rel8      is vexMode=0 & row=7 & cc; rel8                                          { if (cc) goto rel8; }
-:J^cc rel16     is $(LONGMODE_OFF) & vexMode=0 & opsize=0 & byte=0xf; row=8 & cc; rel16  { if (cc) goto rel16; }
+:J^cc rel16_val is $(LONGMODE_OFF) & vexMode=0 & opsize=0 & byte=0xf; row=8 & cc; rel16_val  { if (!cc) goto inst_next; goto [rel16_val]; }
 :J^cc rel32     is vexMode=0 & opsize=1 & byte=0xf; row=8 & cc; rel32                    { if (cc) goto rel32; }
 :J^cc rel32     is vexMode=0 & opsize=2 & byte=0xf; row=8 & cc; rel32                    { if (cc) goto rel32; }
 # The following is vexMode=0 & picked up by the line above.  rel32 works for both 32 and 64 bit
@@ -2841,7 +2857,7 @@
 @endif
 
 :JMP rel8       is vexMode=0 & byte=0xeb; rel8                                  { goto rel8; }
-:JMP rel16      is vexMode=0 & opsize=0 & byte=0xe9; rel16                      { goto rel16; }
+:JMP rel16_val is vexMode=0 & opsize=0 & byte=0xe9; rel16_val                 { goto [rel16_val]; }
 :JMP rel32      is vexMode=0 & opsize=1 & byte=0xe9; rel32                      { goto rel32; }
 :JMP rel32      is vexMode=0 & opsize=2 & byte=0xe9; rel32                      { goto rel32; }
 
@@ -4010,7 +4026,7 @@
 define pcodeop xbegin;
 define pcodeop xend;
 
-:XBEGIN rel16     is vexMode=0 & opsize=0 & byte=0xc7; byte=0xf8; rel16                      { xbegin(&:$(SIZE) rel16); }
+:XBEGIN rel16_val is vexMode=0 & opsize=0 & byte=0xc7; byte=0xf8; rel16_val                  { xbegin(&:$(SIZE) rel16_val); }
 :XBEGIN rel32     is vexMode=0 & (opsize=1 | opsize=2) & byte=0xc7; byte=0xf8; rel32         { xbegin(&:$(SIZE) rel32); }
 
 :XEND            is vexMode=0 & byte=0x0f; byte=0x01; byte=0xd5     { xend(); }

```

**Comment by Wall-AF** [comment]
I don't seem to have 16-bit Real-Mode apps in my suit, mine are all Protected-Mode.  Sorry.

**Comment by carlreinke** [comment]
@emteere That seems to be working quite well so far.

The only oddity is that `JMP rel16` and `CALL rel16` now show as `JMP offset x` and `CALL offset x` rather than `JMP x` and `CALL x`.  (Though I can't say I understand what it means when Ghidra shows `offset x` vs `x` in general.)

Shouldn't `JMP rel8` also have the modified behavior?  It's also not supposed to modify CS.

**Comment by emteere** [comment]
Not having a constant address is the fallout from the change.  For those instruction variants the operand will be a constant display.  If analysis is run it should create a reference if the CS is known.

The offset shows up if the operand is not a Scalar/Address that matches the reference places on the operand.  Displaying offset is not ideal we could doctor the adding of "offset" for segmented addresses, if the offset matches the offset of the destination address.

We also need to add an analyzer that assumes the value of the CS at the beginning of a function.  The Java code has access to the segment value at the address.  The real issue is the information the SLEIGH has doesn't include knowledge of the CS.  It only has the merged seg:off value.

The rel8 is currently a potential issue.  I didn't want to rock the boat too much.  There are issues now with the prefix byte that could cause the segment to start showing up for rel8 in 32/64 bit, which would be bad.  As noted in #5666.  So I left it alone.  I would expect that in most normal code a JMP/CALL rel8 wouldn't be used near the end of a segment to wrap to the beginning of a segment.

**Comment by carlreinke** [comment]
I did find a case where it's still not working as expected, but I'm not sure why.  Evaluating the P-code by hand, it seems like it should do the right thing.
```
       103e:7419 e9 22 01        JMP        offset SUB_19b0_de1e
                                                      $U3880:4 = INT_ZEXT CS
                                                      $U3980:4 = INT_LEFT $U3880:4, 4:4
                                                      $U3a80:4 = INT_SUB 0x1791e:4, $U3980:4
                                                      $U3b00:2 = SUBPIECE $U3a80:4, 0:4
                                                      $U3a80:4 = CALLOTHER "segment", CS, $U3b00:2
                                                      CALLIND $U3a80:4
                                                      RETURN 0:8
                             -- Flow Override: CALL_RETURN (COMPUTED_CALL_TERMINATOR)
```
CS is set to `103e` on this instruction.  The jump destination should be `103e:753e` (`0x1791E`) but instead it ends up with `19b0:de1e` (`0x2791E`).  (`19b0` is the data segment.)
