### ISSUE TITLE
Support for ObjC msgSend stubs

### ISSUE THREAD

**Issue by fmagin** [NationalSecurityAgency/ghidra#5938]
**Is your feature request related to a problem? Please describe.**

iOS Apps compiled with recent versions of XCode can generate stubs for msgSend calls, where each stub is just a call to the actual msgSend address after setting a specific selector:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/8415354/d000d765-5f05-4862-afde-7973627054de)

**Describe the solution you'd like**

 All the stubs are in the `__objc_stubs` section, and this section only contains these kinds of stubs. So they are fairly easy to detect and iterate over, unless that section has been renamed.
Typically the function names also contains the selector, but I have also seen apps where these names were not available, so this can't be relied on.

This has various implications:

- the calling convention of these stubs is weird, because their arguments skip the `x1` register, where the selector will be placed
    - this might mean that a new calling convention needs to be defined for those, where `x1` is skipped 
- they should all be typed as returning the type `ID`, and taking the type `ID` as the first argument, with an unknown amount of additional arguments
- there is the possibility for a simple analysis that recovers the selector for each stub and renames the stub accordingly, if there is no name available
    - this analysis could also infer the number of arguments from the selector, but in _very_ rare cases the selector is obfuscated and the number of colons, doesn't correspond to the number of arguments. So this should be an option of that analysis that can be toggled off, if needed
- there is some logic in Ghidra that resolves msgSend calls to their implementation, this should also apply for these stubs (if the type of the argument can be inferred). But this feature rarely ever worked anyway

**Describe alternatives you've considered**

ObjC is niche, and I can understand if this is too much work that only benefits a rare use case.
I can implement most of these features as an analysis in an extension, but IIRC the calling convention needs to be defined as part of the processor spec, so I can't influence that via an extension. Once that's done I can probably write the rest myself.

**Example app**

[ReverseOneSignal.app.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/13306356/ReverseOneSignal.app.tar.gz), specifically the library `OneSignalLocation`

**Comment by ryanmkurtz** [comment]
Do you know how the calling convention differs on x86?  If we don't have support in a new cspec, can you just use custom storage on each stub?  

This is something I think we'd want to add support for, but i can't really speak to the priority of it right now.  If you aren't opposed to poking at it, we could always try to accept a PR you submit since you expressed interested in implementing it yourself.

**Comment by fmagin** [comment]
> If we don't have support in a new cspec, can you just use custom storage on each stub?

I could use custom storage in theory and this is how I have been handling it so far, but that creates more hassle in practice. I'd also expect that any code that later sets up the arguments gets more complicated then, because it would have to set up the locations manually instead of relying on an existing calling convention.

> Do you know how the calling convention differs on x86?

I think the new "calling convention" for the stubs is just the regular calling convention that is used for `objc_msgSend` except that  the second argument, where the selector will be placed in later, is skipped. Same for the caller and callee saved registers.

**Comment by ryanmkurtz** [comment]
> Can do that to if I get around to it, it also doesn't have super high priority for me right now. Not sure if you want the PR for the compiler spec or the other features

I was mostly asking about the PR because i was assuming this was high priority for you to the point where you'd want to start implementing it now.  If it's more of a get around to it situation for you, I think I'll put it through our prioritization discussion and see how fast I can get to it.  You are not the first person who has asked for improvements in this area.  Maybe we can each just update this ticket if we start working on it.  I'd probably reach out with a question or two if i started it anyway.

**Comment by fmagin** [comment]
It's not high priority and I'm happy to answer questions.

Considering the implementation: I'm using/developing a private plugin anyway, so it's fairly easy for me to write up some janky analysis which works for the binaries I'm looking at, and fix it if I encounter issues. For now it's not even a big enough deal to do that, because I can do it manually for the binary I'm looking at. Having a compiler spec with a calling convention where I don't have to use custom storage would speed up that process a lot already, but it's also the one thing I can't really do from an plugin.

**Comment by AngeloD2022** [comment]
We just published a plugin that aims to help with these annoying things.

https://github.com/ReverseApple/GhidraApple

**Comment by ryanmkurtz** [comment]
@fmagin I'm finally revisiting Ghidra's Objective-C msgSend analyzer, and adding in support for the stubs.  I will likely ask you to take a look at my branch to see what i'm missing and how it can be improved, if you are willing.

For the stubs, do you know if it would ever be safe to rename the stub method to not only include the selector, but also the receiver?  Or, are the stub methods shared across different classes?

**Comment by ryanmkurtz** [comment]
> For the stubs, do you know if it would ever be safe to rename the stub method to not only include the selector, but also the receiver? Or, are the stub methods shared across different classes?

I answered my own question...the stubs are shared for inherited calls.

**Comment by fmagin** [comment]
> the stubs are shared for inherited calls

I don't think it's even limited to inheritance, it's really just the name. This should also ensure uniqueness, i.e. there should never be two stubs calling the same selector, so it should be safe to just rename them the selector (without name collisions).

In our plugin I'm moving them to a dedicated `stub` namespace, to make it easy to distinguish `stub::foobar` from `ReceiverType::foobar` (the latter being the rewritten call to the resolved implementation)

**Comment by ryanmkurtz** [comment]
I also made a "stub" namespace.  I also made a processor extension with a `__objc_msgSend_stub` calling convention to drop the `x1` parameter and treat it as unaffected.  I'm also experimenting with adding `CALL_OVERRIDE_UNCONDITIONAL` references on msgSend calls where I know both the receiver and selector, so the decompiler presents the actual method, rather than the stub.  I still have some work to do with `msgSendSuper` calls, since that parameter list is a little different.

**Comment by fmagin** [comment]
> I also made a processor extension with a `__objc_msgSend_stub` calling convention to drop the `x1` parameter and treat it as unaffected.

Nice, that improves the decompiler quality considerably in my experience.

> I'm also experimenting with adding `CALL_OVERRIDE_UNCONDITIONAL` references on msgSend calls where I know both the receiver and selector, so the decompiler presents the actual method, rather than the stub.

In what cases do you decide to know enough about the receiver type, and how are you handling the ARC calls like `objc_retain` and `objc_storeStrong` during type propagation? I have been dealing with these problems and questions for around 6 years now while doing automated analysis on Objective-C, so I will try to cover what I consider the most important points and my takeaways:

One core problem is what to consider sources of type information without getting into full inter-procedural analysis (unless you want to go there, but I doubt it). Resolving calls to static class methods is easy, constant propagation basically solves this. For object instances one basic approach is to walk the SSA form back to an `objc_alloc` of a concrete class, that's definitely a good start. It gets tricky when dealing when the object is created via a call to static class methods like `new`, `shared`, `sharedInstance`, `instance` or similar. Those can typically return an instance of the class buy just being a wrapper around a `objc_alloc` and a global variable, but that is already a heuristic.

Treating type information from method parameters or instance variables as sources has the problem of dealing with inheritance: The parameter type is just a type bound, and the call might be to a subclass that overrides the method. To really know that you would need to analyze the callers, but for knowing the caller you would need to have resolved the callsites to it already, and now you are dealing with a full-blown inter-procedural and inter-binary type propagation problem that requires a shared model of the Objective-C class hierarchy including inheritance, protocols, categories, etc.

IMO Ghidra itself should provide some UX like in an IDE: If there are multiple possible targets, give the user a short selection of all options and let them select one. Analyzers then populate the DB with possible calls (maybe via some new reference type like `CALL_OVERRIDE_APPROXIMATED`): they could just add all methods in the same binary with a matching name, they could account for inheritance, they could search the imported libraries in the same project for subclasses, they could do full own blown inter-procedural type analysis, etc. This approach would also be reusable for C++ method resolving and allows integration of external analyzers that recover this information externally like [OOAnalyzer](https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ooanalyzer.pod)

**Comment by ryanmkurtz** [comment]
My general goals are:
1. Refactor our existing decompiler-based Objective-C message analyzer, fixing what appears wrong with it along the way
2. Add to the analyzer and introduce a processor extension to better handle the stubs (i.e., this ticket)
3. Add call fixups to the processor extension to clean up the ARC calls
4. Improve the out-of-the-box Objective-C experience to some degree, wherever else possible, without presenting wrong info or going too crazy.

With 3 in mind, I was planning on doing call override stuff only when the basic info i seek is available to me.  The existing analyzer was already laying down comments to show where a msgSend was trying to go to.  I'm basically keeping that logic in tact, but doing a call override instead of just the comment.  If the receiver is found but not the selector, i am going up the superclass hierarchy until it is found, or I hit a class that is not in the binary.  This means that not all msgSends will get a call override.  I am currently experimenting with creating new entries in the EXTERNAL block for methods that aren't found, for the sole purpose of getting the decompiler to look right.  I figure it would be more useful to have the decompiler look right and jump to the EXTERNAL block, rather than just taking you to the msgSend function.  That's still just an experiment though.

**Comment by fmagin** [comment]
>  I am currently experimenting with creating new entries in the EXTERNAL block for methods that aren't found, for the sole purpose of getting the decompiler to look right.

It also allows easier xrefs (i.e. being able to find calls to `NSFileManager::homeDirectoryForCurrentUser` so that is pretty helpful. Plus one can then link the external thunk to the implementation in another `Program` in the Project. I tried this too, the problem I encountered were that it
1. clutters the class view with many external classes
2. Requires an exclusive checkout to extend the EXTERNAL block (IIRC)


I'm really looking forward to your results, I tried doing all of this in our plugin, and there were a lot of design decisions in there that I'm not fully happy with. I'm very curious how someone more familiar with the code-base will approach them.

**Comment by ryanmkurtz** [comment]
> I'm very curious how someone more familiar with the code-base will approach them.

Unfortunately I haven't dealt with analysis much...mostly loaders and other random aspects of Ghidra.  So, some of this is new territory for me too.  

Here's what my basic test program is looking like so far, which uses the stubs:

<img width="422" height="280" alt="Image" src="https://github.com/user-attachments/assets/aedaee05-0b05-4bca-9591-4202ecafca1d" />

The `NSNumber` stuff was put into the EXTERNAL block.  There are definitely going to be issues doing that, but I like the look of it.

Do you mind if I copy the call fixups from your repo that you have already discovered?

**Comment by fmagin** [comment]
> Here's what my basic test program is looking like so far,

`_objc_alloc_init` is common nowadays, but often it's also `IVar1 = objc_alloc` then `IVar1 = objc_msgSend(IVar1, "init")` or `objc_msgSend(IVar1, "initWithArguments", ...)`

Our plugin also traverses methods calls starting with `init` (e.g. `initWithArgument`) to find the intra-procedural allocation. I'd say it's useful enough to at least have it as an option for the analyzer.


> Do you mind if I copy the call fixups from your repo that you have already discovered?

I don't mind, the intellectual effort in creating them was not really relevant. But I would greatly appreciate it if there is a way to credit me for the _idea_ of using the CallFixups feature for this, if I can indeed take the credit for this idea in this context. Just a reference to the DOI of the paper in which we initially formally published the idea would be fine: https://doi.org/10.1109/STATIC66697.2025.00005 

As part of that paper we also created a bunch of [benchmark cases](https://github.com/Fraunhofer-SIT/iFlowBench) for dataflow problems in Objective-C app. Those might be useful to you for testing, though they focus mostly on data flow and not the dynamic dispatch control flow.

**Comment by ryanmkurtz** [comment]
I'd be happy to put links in the javadoc at the top of the analyzer. Ideally the formal publication wouldn't be paywalled.  Is there a link to a more accessible version?  I can also link your RE//verse Langs Beyond the C talk.

**Comment by fmagin** [comment]
Ugh, good point about it not being open access, but I can't change that anymore now. The paper is mostly about dataflow on P-Code, the Objective-C specific idea to use callfixups to quickly model all the ARC functions for the decompiler is only a few paragraphs, but it was relevant because it massively simplified the overall problem. So reading the paper isn't really relevant to understand that approach. I care about the DOI reference for academic/bureaucratic legibility reasons: I can then point to that doc in the Ghidra codebase to argue that my research work was actually relevant for a real world project that people are using. Which is a bar that not many papers published at obscure workshops can clear. It doesn't even have to be a prominent reference in the top level java doc, referencing it in the doc of the function that sets up the fixups would be sufficient, and that same doc could then explain the general idea so that any reader doesn't need to have access to the paper to properly understand it.

**Comment by ryanmkurtz** [comment]
@fmagin if you have some time, would you mind trying out the `msgSend` branch of `git@github.com:ryanmkurtz/ghidra.git`?  All the new behavior is in the "Objective-C Message Analyzer", which I currently have marked as a prototype.  I don't expect it to be perfect...I have kept some logging in that will show what messages failed to get fixed up, for one reason or another.  I would probably turn this off by default in production.

**Comment by fmagin** [comment]
I can test this on real binaries next week, but based on a quick review I've noticed that you are still missing the fixups for the store, load and property getter ARC methods. Is this intentional?

**Comment by ryanmkurtz** [comment]
No, probably just a mistake...I'll take a look, thanks.

**Comment by ryanmkurtz** [comment]
I pushed an update that includes them.

**Comment by fmagin** [comment]
I'm currently giving it a try and it looks good AFAICT, definitely a massive improvement over the previous state.

**Comment by fmagin** [comment]
One issue that I could see is that signatures of the external functions have no arguments. Even if Ghidra treats this as an unknown signature, it will probably still trip up because `x1` is not set for calls via stubs and IME it will then not recognize the passed arguments in `x2`, `x3`, etc. Is it viable to assign the stub calling convention to all external Objective-C methods? I'm not sure if this is just an oversight or a tradeoff because of something else I'm not aware of.

It would also be possible to use the number of arguments that can be inferred via the selector (i.e. the number of `:` characters) to populate the number of arguments of the function. With some heuristics the name for the argument can also be derived.

**Comment by ryanmkurtz** [comment]
Thanks for taking a look...I'm relieved to hear that your inital reaction wasn't that it's a massive fail.  

I originally did add the arguments to the external block, but things actually looked worse in the decompiler, I think because of #8118 (it took the strings away).  So I just kept it simple.  I can definitely add it back in though.

**Comment by fmagin** [comment]
Even if you type the added arguments as `undefined8`? (and not ID, which I think would be incorrect anyway because they can also be primitive types)

**Comment by ryanmkurtz** [comment]
I think I parsed the `::`'s and did `(ID, SEL, undefined8, undefined8, ...)`.  I forget tho, i'll have to put it back in and look at it again.
