### ISSUE TITLE
Function Graph Overlaps Edge Lines

### ISSUE THREAD

**Issue by ebfe2326** [NationalSecurityAgency/ghidra#811]
**Describe the bug**
In the function graph, the edge lines connecting the basic code blocks often overlap and pass straight through code blocks instead of going around.  Many times there can be 4 or 5 edge lines overlapping with no way to distinguish between them.  This makes identifying the code flow very difficult without dragging basic code blocks all over the screen so that the connecting lines move to become visible.  The same issue occurs with edge lines going through the middle of code blocks instead of around.  It's very difficult to identify the end location when the lines pass through intermediate code blocks.

Note that in the attached screenshot, the jump line coming from 0x1000131e is going straight through the code block at the bottom, 0x10001331, and not terminating at that code block.

**Expected behavior**
I'd like the edge lines to not overlap and to ideally go around intermediate code blocks instead of passing straight through the middle.

**Screenshots**
![image](https://user-images.githubusercontent.com/44279601/61556615-3ff9d300-aa30-11e9-999c-00d93ef673b6.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Java Version: openJdk 12
 - Ghidra Version: 9.04

**Comment by dragonmacher** [comment]
Certainly this behavior is binary-specific, but this sort of node overlapping is not the normal case for the Function  Graph.   There is a future that contains more layouts for the Function Graph, which would provide more options to deal with issues like this.   We will also consider how easy it will be to change the edge routing algorithm for this particular layout.

**Comment by ebfe2326** [comment]
i agree this is binary specific, but it seems to occur pretty frequently.  It's good to hear that future releases will contain more layouts for the function graph to deal with this type of issues.  I look forward to the updates.

**Comment by dragonmacher** [comment]
We have added a Tool Option to the Function Graph to address this issue.   Specifically, when enabled, edges will be routed around non-incident vertices.  Also, edges will not overlap the same way as they do with the option disabled.

The option is disabled by default, but can be enabled via:
`Edit -> Tool Options... -> Function Graph -> Nested Code Layout -> Route Edges Around Vertices`

**Comment by ebfe2326** [comment]
thanks for the update.  Is there an expected timeframe when the new version will be released with this update?

**Comment by ryanmkurtz** [comment]
We can't provide a timeframe at this time, but we are working towards a release.  There will probably be a beta period first.  Have you tried building Ghidra yet on your own to test the latest features?

**Comment by ebfe2326** [comment]
I tried building Ghidra myself to test this solution, but I can't get it to build.  I followed the Dev guide for windows.  When I try to build Ghidra, I get an error:
     Execution failed for task: ':PDB:win64PDBMake'
     'Process 'command 'cmd'' finished with non-zero exit value 1

![image](https://user-images.githubusercontent.com/44279601/63653563-6a7c3180-c73c-11e9-9b93-aa17cd0d0290.png)

I'm running the command, gradle buildGhidra from a git-bash console and have tried it both as a regular user and admin.  In either case I get the same error.

Do you have any idea what I'm doing wrong?

**Comment by kant2002** [comment]
@ebfe2326 Examine file in the project
`Ghidra/Features/PDB/build/buildSolution.bat`
Try to run that bat file, it is the reason for your failure.

**Comment by ebfe2326** [comment]
With the error occurring in my last comment.  I noticed in the output just after I ran the gradle buildGhidra command, it's listing my visual studio SDK as version 10 instead of version 8.1  I installed version 8.1 and confirmed I can select it for any given project within visual studio.  It looks to me like the gradle script may somehow be using SDK 10 as the default instead of SDK 8.1.  Do you think that could be a cause of the error, or is that just a misleading output string?

If you think this might be a cause of the error, is there a way to tell the gradle script to use SDK 8.1 instead of 10?  I can easily change the SDK version per project, but I haven't seen any setting that forces the default version to be 8.1.  

![image](https://user-images.githubusercontent.com/44279601/63966665-be06bc00-ca69-11e9-8a94-d47cb1d8e07d.png)
...
![image](https://user-images.githubusercontent.com/44279601/63966813-1a69db80-ca6a-11e9-8ab2-73079e34ab06.png)

**Comment by ryanmkurtz** [comment]
Unfortunately I'm out of ideas for why your setup isn't building.  We can continue discussing it here, but I'm going to close the ticket because the function graph thing has been fixed for 9.1.

**Comment by ebfe2326** [comment]
thanks for all the help.  let me ask one more quick question about the build setup and then i'll play with it some more and open up a separate ticket if needed just for the build.

I built a brand new windows 10 VM and installed everything from scratch, but still having issues with Visual Studio's install.  I only installed SDK 8.1, but receive the error below.  Two things look strange.  It's listing the Windows SDK version as blank instead of recognizing 8.1 SDK and the actual search path is looking the windows 10 path inside of the windows kits directory instead of the 8.1 path.  If I build a new project in visual studio, i confirmed that SDK 8.1 is installed and there is no option for 10.0  When I look at the windows kits directory, I see a folder for both 8.1 and 10 even though i made sure I didn't have any selection for SDK 10 when installing my fresh copy of visual studio.

It seems apparent I need to install Visual studio's in a different way.  Are you able to provide any specifics about exactly what components of Visual Studio I need to install?  When I installed it for this fresh VM, i selected the "Desktop developt with c++" under the workloads and then unselected all SDK 10 version under the individual components section.  If you installed a different workload or chose specific individual components, i can replicate whatever you have and try again.

![image](https://user-images.githubusercontent.com/44279601/64304526-2964f800-cf5a-11e9-8306-33c2214abc85.png)

![image](https://user-images.githubusercontent.com/44279601/64304682-c6c02c00-cf5a-11e9-8e0d-a423bf1c91cc.png)

**Comment by ryanmkurtz** [comment]
It looks like your latest errors have to do with not being able to build for the 64-bit platform.  

When I installed VS17 Community, I check .NET desktop development and Desktop development with C++, and then i also add Windows 8.1 SDK and UCT SDK.  I leave Windows 10 SDK checked.  I'm not sure if .NET is required, but I wanted to have it for other things.

**Comment by ebfe2326** [comment]
thanks for all the help.  Good news is I was able to build the project based off how you installed visual studio!  

I installed Visual Studio 2017 Community Edition (version 15.9) with the following options:  
For the workloads, I installed 
- .NET Desktop Development
- Desktop Development with C++
For the individual components, I left everything as default and added:
- Windows 8.1 SDK
- Windows Universal CRT SDK

I would highly suggest updating the build instructions to make it clear these components are needed in the visual studio install.

I also checked out the new graph mode.  It's monumentally better.  After a quick check, there are still a few minor improvements I would suggest, but they are only minor.  Do you think it's worth adding the potential improvements in case they're an easy tweak prior to the next build version being released?  If so, should I add them here since this ticket was originally for the graphing, or should I open a new feature request to highlight the tweaks?

Thanks again for all your help!

**Comment by ryanmkurtz** [comment]
Glad you got it working!  I'll try to incorporate some of this into the DevGuide. 

I think it would be best if you make a new enhancement ticket for any new graphing changes.
