### ISSUE TITLE
Structure Editor moves when double clicking table cells

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#8603]
**Describe the bug**
Double clicking a cell in the structure editor causes it to jump around causing the second click to be somewhere else making it difficult to edit what I want to edit.

**To Reproduce**
1. Double click a cell in the structure editor of a structure with several fields (enough that you can scroll through them in the window.

**Expected behavior**
Don't move, I didn't scroll anywhere.

**Environment (please complete the following information):**
 - OS: Win 10 1809
 - Java Version: 21
 - Ghidra Version: 12.1_DEV

**Comment by dragonmacher** [comment]
I have not seen this before.   Can you post something that shows the behavior?

**Comment by astrelsky** [comment]
> I have not seen this before.   Can you post something that shows the behavior?

I can do so in a few hours, maybe try it in the debugger instead of the code browser, it might be something related to things going on there. I'm currently neck deep in a debugging session and starting to forget my own name. You wouldn't need the debugger running.

It's pretty simple to reproduce though. Scroll to the last field in a structure of 100 fields and then click on the highest visible field and watch it move the scroll position so that field is centered.

**Comment by astrelsky** [comment]
https://github.com/user-attachments/assets/b3c330f4-8a20-4e74-922e-d5e41a37a9d6

I just pulled and built it, so it's still present in master at 4b1fd225467d18aa664adf6cdc68a43fdd3e5025. All I'm doing is clicking on the field, nothing else. This is a different machine then what I was using earlier too.

**Comment by dragonmacher** [comment]
I see it now. I think I broke these with a new mouse listener recently.

Thanks.

**Comment by nmggithub** [comment]
I can second that I'm experiencing this too (built from latest `master`). I was experiencing some performance issues so I upgraded everything (Ghidra, JDK, Gradle, Kotlin (for my extension I'm maintaining), etc.) and I wasn't sure where the source of this was. All signs point to this being a Ghidra issue since you're experiencing this on JDK 21 (and I upgraded from JDK 23 to 25 along with upgrading Ghidra).

**Comment by dragonmacher** [comment]
Thanks for the update.  This has been fixed in master, but not yet uploaded to github.

**Comment by astrelsky** [comment]
@dragonmacher I saw the commit. I haven't tested it yet, but this behavior was seen in other places too. I think the strings table was one of them, but I'm not 100% sure.

**Comment by dragonmacher** [comment]
The fix I made was for something I broke specifically in the structure editor.  If this problem exists elsewhere, then it is a different issue.  Let us know if and where you see it.

**Comment by astrelsky** [comment]
> The fix I made was for something I broke specifically in the structure editor.  If this problem exists elsewhere, then it is a different issue.  Let us know if and where you see it.


It's present in the strings table too. The defined data table doesn't have this issue.


Unrelated:

Oh look, the symbol table filter is missing. I completely forget what was recommended I try when it happens again :joy:. If I take a snapshot of them symbol tree window it appears in the snapshot, but no matter what it doesn't appear in the current symbol tree. Log shows nothing of interest. Closing and reopening the code browser is the only thing that fixes it.

**Comment by dt-12345** [comment]
The issue still seems to be present in the latest commit both in the structure editor and defined strings table.

**Comment by astrelsky** [comment]
> The issue still seems to be present in the latest commit both in the structure editor and defined strings table.

I didn't encounter it in the structure editor in the latest commit.

**Comment by dragonmacher** [comment]
> Oh look, the symbol table filter is missing. 

There is now an action to show and hide the tree filters.   This issue existed before that actions was created.  But, I'd hope that use that action will fix the issue.   It should be available via a right-click on the Symbol Tree.

**Comment by dt-12345** [comment]
> > The issue still seems to be present in the latest commit both in the structure editor and defined strings table.
> 
> I didn't encounter it in the structure editor in the latest commit.

Huh, not sure what happened but it seems to be fine now that I've tried it again. The issue with the defined strings table still remains as expected.

**Comment by dragonmacher** [comment]
Looks like the Strings table has a feedback problem.  As you click, a navigation happens, which updates the view.   I should be able to fix that.

**Comment by dragonmacher** [comment]
The Structure Editor is fixed by 2c13b126013cc8a228d2c33e6243c157155bd4ba
